- name: Install gui packages
  apt:
      name: "{{ item }}"
  with_items:
      - "{{ gui_apps }}"
  become: true

- name: Copy i3 config
  copy:
        src: "i3config"
        dest: "/home/{{ username }}/.config/i3/config"

- name: Install Steam
  apt:
        deb: "https://steamcdn-a.akamaihd.net/client/installer/steam.deb"
  become: true
