- name: install cli apps
  become: true
  apt:
      name: "{{ item }}"
  with_items: "{{ cli_apps }}"

- name: set shell to zsh
  become: true
  user:
      name: "{{ username }}"
      shell: /bin/zsh

- name: install fzf
  block:
      - git:
          repo: "https://github.com/junegunn/fzf.git"
          depth: 1
          dest: "~/.fzf"
      - shell: ~/.fzf/install --all
