- name: install cli apps
  become: true
  apt:
      name: "{{ item }}"
  with_items: "{{ cli_apps }}"

- name: set vim up
  block:
      - copy:
          src: ".vimrc"
          dest: "/home/{{ username }}/.vimrc"
        name: Copy vimrc
      - shell: vim +PluginInstall +qall!
        args:
            creates: "/home/{{ username }}/.vim/bundle/vim-fugitive/"
        name: Install vim plugins

- name: set shell to zsh
  become: true
  user:
      name: "{{ username }}"
      shell: /bin/zsh

- name: install fzf
  block:
      - git:
          repo: "https://github.com/junegunn/fzf.git"
          depth: 1
          dest: "~/.fzf"
        name: Clone fzf
      - shell: ~/.fzf/install --all
        args:
            creates: "/home/{{ username }}/.fzf/bin/fzf"
        name: Install fzf
